name: Build LaTeX Documents

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install TikZ dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full biber

      - name: List project structure (for debugging)
        run: |
          find . -type f -name "*.png" | sort
          find . -type f -name "*.bib" | sort
          
      - name: Compile memoire document
        run: |
          # Navigate to the memoire directory
          cd latex/memoire
          
          # Debug - list files in current directory
          echo "Contents of latex/memoire:"
          ls -la
          
          # Make sure the images directory exists
          if [ ! -f "scan_setup.png" ]; then
            echo "Warning: scan_setup.png not found in current directory"
            echo "Searching for the file elsewhere..."
            find ../../ -name "scan_setup.png"
          fi
          
          # Compile the main document with more verbose output
          latexmk -pdf -bibtex -verbose main.tex || true
          
          # Check if bibliography files exist
          if [ -f "main.bib" ]; then
            echo "Bibliography file exists"
          else
            echo "Warning: main.bib not found"
            find ../../ -name "*.bib"
          fi
          
          # Run multiple passes to ensure all references are resolved
          pdflatex -interaction=nonstopmode main.tex || true
          biber main || true
          pdflatex -interaction=nonstopmode main.tex || true
          pdflatex -interaction=nonstopmode main.tex || true
          
          # Check if PDF was generated
          if [ -f "main.pdf" ]; then
            echo "PDF successfully generated"
            mkdir -p ../../static/pdfs
            cp main.pdf ../../static/pdfs/memoire.pdf
          else
            echo "Error: PDF was not generated"
            cat main.log
            exit 1
          fi
      
      - name: Compile Machine Guide document
        run: |
          # Navigate to the setup directory
          cd latex/setup
          
          # Debug - list files in current directory
          echo "Contents of latex/setup:"
          ls -la
          
          # Compile the main document with more verbose output
          latexmk -pdf -bibtex -verbose main.tex || true
          
          # Run multiple passes to ensure all references are resolved
          pdflatex -interaction=nonstopmode main.tex || true
          biber main || true
          pdflatex -interaction=nonstopmode main.tex || true
          pdflatex -interaction=nonstopmode main.tex || true
          
          # Check if PDF was generated
          if [ -f "main.pdf" ]; then
            echo "PDF successfully generated"
            mkdir -p ../../static/pdfs
            cp main.pdf ../../static/pdfs/setup.pdf
          else
            echo "Error: PDF was not generated"
            cat main.log
            exit 1
          fi
          
      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: latex-pdfs
          path: |
            static/pdfs/memoire.pdf
            static/pdfs/setup.pdf
